### ISSUE TITLE
Missing zip files while downloading the database 

### ISSUE THREAD

**Issue by sumeetssaurav** [STAIR-Lab-CIT/STAIR-actions#3]
Hello,

I am trying to download the STAIR database. However, some of the class files are not available. However, from the training and validation list there is presence of the database. Please suggest me a proper patch for the same.

Thanking You

**Comment by yuyay** [comment]
Hi @sumeetssaurav,

Do you mean that some videos are missing?
Unfortunately, some videos especially from YouTube cannot be downloaded because their original videos on YouTube have been already deleted, or some reasons.
Please use [data/videolist_train.txt](https://github.com/STAIR-Lab-CIT/STAIR-actions/blob/master/data/videolist_train.txt) and [data/videolist_val.txt](https://github.com/STAIR-Lab-CIT/STAIR-actions/blob/master/data/videolist_val.txt) by removing lines of the videos which cannot be downloaded.

Thank you.

**Comment by sumeetssaurav** [comment]
Hello,
I could just be able to download 64331 videos. There are nearly 20 classes having no videos. Unfortunately, now we can say that the STAIR dataset has only 80 classes. It will greatly affect the whole purpose of the dataset. What is gonna be your future plans for extending the database...?

**Comment by yuyay** [comment]
Hi @sumeetssaurav,

Sorry for inconvenience.
Probably you failed to download YouTube videos.
(I think your downloaded videos are named as "*C.mp4")
Please check out whether youtube-dl is already installed.
If it is already installed, please upgrade youtube-dl to the latest version.
Otherwise, install youtube-dl.

Then, could you retry the following command?
```
bash download.sh
```

Thank you.

**Comment by sumeetssaurav** [comment]
Hii,
Thankx for the quick reply. One more doubt. What I see from the download.sh file is: The original videos with extension "C.mp4" will be first downloaded. Once it get complete, the youtube videos will be downloaded. I just want to know whether I am right or not?? This is because I have to wait for days to check whether the youtube videos are getting downloaded or not.

**Comment by yuyay** [comment]
Hi @sumeetssaurav,

> The original videos with extension "C.mp4" will be first downloaded. Once it get complete, the youtube videos will be downloaded. I just want to know whether I am right or not?? 

That's right. So, I think you can skip lines 14-30 of [download.sh](https://github.com/STAIR-Lab-CIT/STAIR-actions/blob/master/download.sh).

Thank you.
