### ISSUE TITLE
Missing data in original videos

### ISSUE THREAD

**Issue by imanishikayac** [STAIR-Lab-CIT/STAIR-actions#6]
Hello, Thanks for providing a nice dataset!

I am trying to download the original data of a001-a120, but some data sets seem to be missing.

ex) a011,cooking (and more, about 20 labels..)

Are these data not available?

**Comment by yuyay** [comment]
Hi @imanishikayac,

Thanks for your comment.
Do you mention a zip file downloaded from https://data.airc.aist.go.jp/stair-actions-v1.1/train/cooking.zip ?
The zip file contains only an empty directory because there is no *not-YouTube* videos.
Thus, the downloader behaves normally.
The videos associated with *cooking* category will be downloaded from YouTube in the later process in `download.sh`.

**Comment by imanishikayac** [comment]
Thank you for your quick reply!

The issue was solved!
Sorry for my lack of understanding.

Thanks :)
